# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763c0f98558a32a98b1a0186f04bf113774c639698dc740e75465f936752111706c390eda9f6a6766faacabb562f3eb36f4ca56e7632cfcf59dccfe673fdb06d

test:
  secret_key_base: 2e5fb21abf661777495067ceda2dbd4e6b61f2892212217bb437dc6416ca058f08540d75d520a3645f677027f48dd4b128b62305e018ba99471b574743642db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
